config/routes.rb
Rails.application.routes.draw do
  resources :unavailable_dates
  get 'sessions/new'
  
  root 'static_pages#home'
  get 'help'  => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  delete 'violated_brand' => 'users#destroy_brand'
  get 'add_violated_brand' => 'users#add_violated_brand'
  get 'add_item' => 'items#add'
  post 'update_price' => 'items#update_price'
  post 'add_from_SYW' => 'items#add_from_SYW'
  post 'clean' => 'items#clean'
  get 'add_from_SYW' => 'items#add_item'
  post 'add_list_from_SYW' => 'items#add_list_from_SYW'
  get 'query_result' => 'items#query'
  post 'update_description' => 'items#update_description'
  delete 'items' => 'items#destroy'
  resources :users
  resources :items
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The cloud version of ebay manager.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact")%>
<h1>Contact</h1>
<p>
	Contact Mr Mai about the use of the web app
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the eBay Manager from myh0209@gmail.com.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to the eBayManager</h1>

	<p>
  	  This is the home page for the ebay application.
	</p>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("COWEN.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>