config/routes.rb
Rails.application.routes.draw do
  resources :unavailable_dates
  get 'sessions/new'
  
  root 'static_pages#home'
  get 'help'  => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  delete 'violated_brand' => 'users#destroy_brand'
  get 'add_violated_brand' => 'users#add_violated_brand'
  get 'add_item' => 'items#add'
  post 'update_price' => 'items#update_price'
  post 'add_from_SYW' => 'items#add_from_SYW'
  post 'clean' => 'items#clean'
  get 'add_from_SYW' => 'items#add_item'
  post 'add_list_from_SYW' => 'items#add_list_from_SYW'
  get 'query_result' => 'items#query'
  post 'update_description' => 'items#update_description'
  delete 'items' => 'items#destroy'
  resources :users
  resources :items
  

end

app/models/unavailable_date.rb
class UnavailableDate < ActiveRecord::Base
end

app/controllers/unavailable_dates_controller.rb
class UnavailableDatesController < ApplicationController
  before_action :set_unavailable_date, only: [:show, :edit, :update, :destroy]

  # GET /unavailable_dates
  # GET /unavailable_dates.json
  def index
    @unavailable_dates = UnavailableDate.all
  end

  # GET /unavailable_dates/1
  # GET /unavailable_dates/1.json
  def show
  end

  # GET /unavailable_dates/new
  def new
    @unavailable_date = UnavailableDate.new
  end

  # GET /unavailable_dates/1/edit
  def edit
  end

  # POST /unavailable_dates
  # POST /unavailable_dates.json
  def create
    @unavailable_date = UnavailableDate.new(unavailable_date_params)

    respond_to do |format|
      if @unavailable_date.save
        format.html { redirect_to @unavailable_date, notice: 'Unavailable date was successfully created.' }
        format.json { render :show, status: :created, location: @unavailable_date }
      else
        format.html { render :new }
        format.json { render json: @unavailable_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unavailable_dates/1
  # PATCH/PUT /unavailable_dates/1.json
  def update
    respond_to do |format|
      if @unavailable_date.update(unavailable_date_params)
        format.html { redirect_to @unavailable_date, notice: 'Unavailable date was successfully updated.' }
        format.json { render :show, status: :ok, location: @unavailable_date }
      else
        format.html { render :edit }
        format.json { render json: @unavailable_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unavailable_dates/1
  # DELETE /unavailable_dates/1.json
  def destroy
    @unavailable_date.destroy
    respond_to do |format|
      format.html { redirect_to unavailable_dates_url, notice: 'Unavailable date was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unavailable_date
      @unavailable_date = UnavailableDate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unavailable_date_params
      params.require(:unavailable_date).permit(:ebayID, :unavailable_date)
    end
end

app/helpers/unavailable_dates_helper.rb
module UnavailableDatesHelper
end

app/views/unavailable_dates/_form.html.erb
<%= form_for(@unavailable_date) do |f| %>
  <% if @unavailable_date.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unavailable_date.errors.count, "error") %> prohibited this unavailable_date from being saved:</h2>

      <ul>
      <% @unavailable_date.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ebayID %><br>
    <%= f.text_field :ebayID %>
  </div>
  <div class="field">
    <%= f.label :unavailable_date %><br>
    <%= f.text_field :unavailable_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unavailable_dates/edit.html.erb
<h1>Editing Unavailable Date</h1>

<%= render 'form' %>

<%= link_to 'Show', @unavailable_date %> |
<%= link_to 'Back', unavailable_dates_path %>

app/views/unavailable_dates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Unavailable Dates</h1>

<table>
  <thead>
    <tr>
      <th>Ebayid</th>
      <th>Unavailable date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unavailable_dates.each do |unavailable_date| %>
      <tr>
        <td><%= unavailable_date.ebayID %></td>
        <td><%= unavailable_date.unavailable_date %></td>
        <td><%= link_to 'Show', unavailable_date %></td>
        <td><%= link_to 'Edit', edit_unavailable_date_path(unavailable_date) %></td>
        <td><%= link_to 'Destroy', unavailable_date, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unavailable date', new_unavailable_date_path %>

app/views/unavailable_dates/new.html.erb
<h1>New Unavailable Date</h1>

<%= render 'form' %>

<%= link_to 'Back', unavailable_dates_path %>

app/views/unavailable_dates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ebayid:</strong>
  <%= @unavailable_date.ebayID %>
</p>

<p>
  <strong>Unavailable date:</strong>
  <%= @unavailable_date.unavailable_date %>
</p>

<%= link_to 'Edit', edit_unavailable_date_path(@unavailable_date) %> |
<%= link_to 'Back', unavailable_dates_path %>